language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install --prefer-source
  
script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run